# Site Settings
baseurl: ""
url : "https://marcosbergami.github.io"

# Blog Settings
theme_settings :
  title : Let The Journey Begin!
  favicon : assets/pagesfavicon.ico

  # Profile Settings
  profile :
    image : assets/img/profilepic.png
    username : Marcos Bergami
    description : Computer Science Student on the road to become a Full Stack Developer.
    experience :
      - start :
        end :
        experience :
    skills : 
      - skill : NodeJS & ReactJS
        value : 85  # Percent value
        
  # Icons
  icons :
    email: marcos@mogri.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: marcosbergami
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: bergami_marcos
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
